<div style="border:solid green 2px; padding: 20px"> 
Oi Gerson, tudo bem? 
    
Me chamo Lourenço, vou ser o corretor em português do seu projeto! Prazer em conhecê-lo! 🙌 
 
Meus comentários irão seguir a mesma lógica dos feitos pelo corretor antigo:

<div class="alert alert-success">
    <b>Correto:</b> Cumpriu corretamente tudo que foi pedido
</div>
<div class="alert alert-warning">
    <b>Recomendação:</b> Existe espaço para melhoramento do código
</div>
<div class="alert alert-danger">
    <b>Precisa ser corrigido:</b> Esse tipo de comentário ocorre quando o código precisa de alguma mudança drástica. O projeto não pode ser aceito com comentários vermelhos.
</div>
    
Por favor, não delete meus comentários :) Se tiver alguma pergunta, basta respondê-los.

<div class="alert alert-block alert-danger">
<b>Comentário geral do corretor</b> <a class="tocSkip"></a>

Gerson,  primeiramente muito obrigado por enviar o seu projeto! Está claro para mim seu empenho em fazê-lo.
    
<br />
    
Seu projeto está muito bom! Você fez bom uso das principais técnicas requeridas neste projeto, deixou o código bem organizado e bem documentado. Existe uma pequeníssima coisa a ser corrigida: tratar os dados para o número de 20 filhos, que é anormal para a porcentagem dos dados que eles representam!
    
<br />
    
Assim que corrigir este problema, que será uma tarefa simples para você, terá seu projeto aprovado. Bons estudos!   
    
</div>

<div class="alert alert-block alert-success">
<b>Comentário geral do corretor</b> <a class="tocSkip"></a>

Após sua correção muito bem realizada e comentada, seu projeto será aprovado! Parabéns!
    
Espero que continue com esse ritmo nos próximos módulos e que seu aprendizado continue sendo frutífero. Bons estudos!    
    
</div>

# Análise do risco de inadimplência dos mutuários

Seu projeto é preparar um relatório para a divisão de empréstimos de um banco. Você precisará descobrir se o estado civil de um cliente e o número de filhos têm impacto sobre se ele deixará de pagar um empréstimo. O banco já tem alguns dados sobre a capacidade de crédito dos clientes.

Seu relatório será considerado ao criar uma **pontuação de crédito** de um cliente em potencial. A **contagem de crédito** é usada para avaliar a capacidade de um devedor em potencial de pagar seu empréstimo.

[Antes de mergulhar na análise de seus dados, explique os propósitos do projeto e as hipóteses que você testará.]

**A análise consiste em verificar as seguintes hipotestes:**

1. Existe uma correlação entre o nível de renda e do pagamento em dia?
2. Existe uma correlação entre o status familiar e o pagamento em dia?
3. Existe uma correlação entre o status familiar e o pagamento em dia?

## Abra o arquivo de dados e veja as informações gerais.


In [1]:
# Carregando todas as bibliotecas
import pandas as pd

# Carregue os dados
try:
    # Carregar localmente, como são apenas 2mb descartei o download do ficheiro
    df = pd.read_csv('https://code.s3.yandex.net/datasets/credit_scoring_eng.csv') 
except:
    df = pd.read_csv('/datasets/credit_scoring_eng.csv')

print('Dataframe carregado!')

Dataframe carregado!


## Tarefa 1. Exploração de dados

**Descrição dos dados**
- `children` - o número de crianças na família
- `days_employed` - experiência de trabalho em dias
- `dob_years` - idade do cliente em anos
- `education` - educação do cliente
- `education_id` - identificador de educação
- `family_status` - estado civil do cliente
- `family_status_id` - identificador de estado civil
- `gender` - gênero do cliente
- `income_type` - tipo de emprego
- `debt` - havia alguma dívida no pagamento do empréstimo
- `total_income` - renda mensal
- `purpose` - o objetivo de obter um empréstimo


<a id='linhasDfOriginal'></a>

In [2]:
# Vamos ver quantas linhas e colunas nosso conjunto de dados tem

total_linhas_df_orig = len(df)

total_colunas_df_orig = df.shape[1]


print(f'O dataset tem {total_linhas_df_orig} linhas e {total_colunas_df_orig} colunas.')

O dataset tem 21525 linhas e 12 colunas.


In [3]:
# vamos exibir as primeiras N linhas

df.head(15)


children  days_employed  dob_years            education  education_id  \
0          1   -8437.673028         42    bachelor's degree             0   
1          1   -4024.803754         36  secondary education             1   
2          0   -5623.422610         33  Secondary Education             1   
3          3   -4124.747207         32  secondary education             1   
4          0  340266.072047         53  secondary education             1   
5          0    -926.185831         27    bachelor's degree             0   
6          0   -2879.202052         43    bachelor's degree             0   
7          0    -152.779569         50  SECONDARY EDUCATION             1   
8          2   -6929.865299         35    BACHELOR'S DEGREE             0   
9          0   -2188.756445         41  secondary education             1   
10         2   -4171.483647         36    bachelor's degree             0   
11         0    -792.701887         40  secondary education             1   
12         0            NaN         65  secondary education             1   
13         0   -1846.641941         54         some college             2   
14         0   -1844.956182         56    bachelor's degree             0   

        family_status  family_status_id gender income_type  debt  \
0             married                 0      F    employee     0   
1             married                 0      F    employee     0   
2             married                 0      M    employee     0   
3             married                 0      M    employee     0   
4   civil partnership                 1      F     retiree     0   
5   civil partnership                 1      M    business     0   
6             married                 0      F    business     0   
7             married                 0      M    employee     0   
8   civil partnership                 1      F    employee     0   
9             married                 0      M    employee     0   
10            married                 0      M    business     0   
11            married                 0      F    employee     0   
12  civil partnership                 1      M     retiree     0   
13            married                 0      F    employee     0   
14  civil partnership                 1      F    business     1   

    total_income                              purpose  
0      40620.102                purchase of the house  
1      17932.802                         car purchase  
2      23341.752                purchase of the house  
3      42820.568              supplementary education  
4      25378.572                    to have a wedding  
5      40922.170                purchase of the house  
6      38484.156                 housing transactions  
7      21731.829                            education  
8      15337.093                     having a wedding  
9      23108.150  purchase of the house for my family  
10     18230.959                      buy real estate  
11     12331.077           buy commercial real estate  
12           NaN                    to have a wedding  
13     20873.317                         car purchase  
14     26420.466          buy residential real estate

### Observações na amostra das primeiras 15 linhas
* A coluna  `days_employed` 
tem valores <font color=red>negativos</font> e valores nulos (`NaN`)
* A coluna `education` <font color=red>não esta uniformizado</font> e pode ser categorizado de melhor forma, exemplo: 'secondary education' & 'Secondary Education' representam o mesmo nível de educação academica, a coluna `education_id` pode ajudar a corrigir os dados
* Com sorte conseguimos apanhar um valor nulo (`NaN`) nas primeiras 15 linhas para a coluna `total_income` e corresponde ao mesmo registo com nulo para a coluna `days_employed` podemos analisar se esta combinação quer dizer que a pessoa esta desempregada 
* A coluna `purpose` pode ser uniformizada a depender se forem poucos valores unicos, exemplo: <font color=blue>*'purchase of the house'*</font> & <font color=blue>*'purchase of the house for my family'*</font> & <font color=blue>*'buy residential real estate'*</font> numa primeira observação pode significar o mesmo objetivo para obtenção do credito
***

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Ótima observação inicial dos dados!

</div>

In [4]:
# Obter informações sobre dados
df.info()

df.describe()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


children  days_employed     dob_years  education_id  \
count  21525.000000   19351.000000  21525.000000  21525.000000   
mean       0.538908   63046.497661     43.293380      0.817236   
std        1.381587  140827.311974     12.574584      0.548138   
min       -1.000000  -18388.949901      0.000000      0.000000   
25%        0.000000   -2747.423625     33.000000      1.000000   
50%        0.000000   -1203.369529     42.000000      1.000000   
75%        1.000000    -291.095954     53.000000      1.000000   
max       20.000000  401755.400475     75.000000      4.000000   

       family_status_id          debt   total_income  
count      21525.000000  21525.000000   19351.000000  
mean           0.972544      0.080883   26787.568355  
std            1.420324      0.272661   16475.450632  
min            0.000000      0.000000    3306.762000  
25%            0.000000      0.000000   16488.504500  
50%            0.000000      0.000000   23202.870000  
75%            1.000000      0.000000   32549.611000  
max            4.000000      1.000000  362496.645000

### Com a informação acima podemos confirmar as  seguintes observações:
* As unicas colunas que não estão com dados completos são `days_employed` e `total_income`.
* A Coluna `children` (número de crinças na familia) tem o valor minimo <font color=red> **-1**</font>  que não faz muito sentino até o momento.

* A coluna `dob_years` (idade do cliente em anos) tem o valor minimo **0**, é preciso investigar o significado destes registos.



In [5]:
# Vejamos a tabela filtrada com valores ausentes na primeira coluna com dados ausentes

df_employed_null = df[df['days_employed'].isna()]

df_employed_null

children  days_employed  dob_years            education  education_id  \
12            0            NaN         65  secondary education             1   
26            0            NaN         41  secondary education             1   
29            0            NaN         63  secondary education             1   
41            0            NaN         50  secondary education             1   
55            0            NaN         54  secondary education             1   
...         ...            ...        ...                  ...           ...   
21489         2            NaN         47  Secondary Education             1   
21495         1            NaN         50  secondary education             1   
21497         0            NaN         48    BACHELOR'S DEGREE             0   
21502         1            NaN         42  secondary education             1   
21510         2            NaN         28  secondary education             1   

           family_status  family_status_id gender    income_type  debt  \
12     civil partnership                 1      M        retiree     0   
26               married                 0      M  civil servant     0   
29             unmarried                 4      F        retiree     0   
41               married                 0      F  civil servant     0   
55     civil partnership                 1      F        retiree     1   
...                  ...               ...    ...            ...   ...   
21489            married                 0      M       business     0   
21495  civil partnership                 1      F       employee     0   
21497            married                 0      F       business     0   
21502            married                 0      F       employee     0   
21510            married                 0      F       employee     0   

       total_income                   purpose  
12              NaN         to have a wedding  
26              NaN                 education  
29              NaN    building a real estate  
41              NaN  second-hand car purchase  
55              NaN         to have a wedding  
...             ...                       ...  
21489           NaN         purchase of a car  
21495           NaN          wedding ceremony  
21497           NaN       building a property  
21502           NaN    building a real estate  
21510           NaN              car purchase  

[2174 rows x 12 columns]


### Analisando os valores ausentes na coluna `days_employed`

* Para todos os valores apresentados na amostra acima, a coluna `total_income` também apresenta <font color=red>valores ausentes</font>, vamos confirmar esta hipotese com mais alguns filtros no dataframe original

In [6]:
len(df_employed_null)

2174

**Existem 2174 <font color=red>valores ausentes</font> pela coluna `days_employed`**

In [7]:
# Vamos aplicar várias condições para filtrar dados e observar o número de linhas na tabela filtrada.

df [ (df.total_income.isna()) ]

children  days_employed  dob_years            education  education_id  \
12            0            NaN         65  secondary education             1   
26            0            NaN         41  secondary education             1   
29            0            NaN         63  secondary education             1   
41            0            NaN         50  secondary education             1   
55            0            NaN         54  secondary education             1   
...         ...            ...        ...                  ...           ...   
21489         2            NaN         47  Secondary Education             1   
21495         1            NaN         50  secondary education             1   
21497         0            NaN         48    BACHELOR'S DEGREE             0   
21502         1            NaN         42  secondary education             1   
21510         2            NaN         28  secondary education             1   

           family_status  family_status_id gender    income_type  debt  \
12     civil partnership                 1      M        retiree     0   
26               married                 0      M  civil servant     0   
29             unmarried                 4      F        retiree     0   
41               married                 0      F  civil servant     0   
55     civil partnership                 1      F        retiree     1   
...                  ...               ...    ...            ...   ...   
21489            married                 0      M       business     0   
21495  civil partnership                 1      F       employee     0   
21497            married                 0      F       business     0   
21502            married                 0      F       employee     0   
21510            married                 0      F       employee     0   

       total_income                   purpose  
12              NaN         to have a wedding  
26              NaN                 education  
29              NaN    building a real estate  
41              NaN  second-hand car purchase  
55              NaN         to have a wedding  
...             ...                       ...  
21489           NaN         purchase of a car  
21495           NaN          wedding ceremony  
21497           NaN       building a property  
21502           NaN    building a real estate  
21510           NaN              car purchase  

[2174 rows x 12 columns]

In [8]:
df.total_income.isna().sum()

2174

**Existem 2174 <font color=red>valores ausentes</font> pela coluna `total_income`**

#### Filtro para valores ausentes nas colunas `total_income` & `days_employed`

In [9]:
df [ (df.total_income.isna()) & (df.days_employed.isna()) ]

children  days_employed  dob_years            education  education_id  \
12            0            NaN         65  secondary education             1   
26            0            NaN         41  secondary education             1   
29            0            NaN         63  secondary education             1   
41            0            NaN         50  secondary education             1   
55            0            NaN         54  secondary education             1   
...         ...            ...        ...                  ...           ...   
21489         2            NaN         47  Secondary Education             1   
21495         1            NaN         50  secondary education             1   
21497         0            NaN         48    BACHELOR'S DEGREE             0   
21502         1            NaN         42  secondary education             1   
21510         2            NaN         28  secondary education             1   

           family_status  family_status_id gender    income_type  debt  \
12     civil partnership                 1      M        retiree     0   
26               married                 0      M  civil servant     0   
29             unmarried                 4      F        retiree     0   
41               married                 0      F  civil servant     0   
55     civil partnership                 1      F        retiree     1   
...                  ...               ...    ...            ...   ...   
21489            married                 0      M       business     0   
21495  civil partnership                 1      F       employee     0   
21497            married                 0      F       business     0   
21502            married                 0      F       employee     0   
21510            married                 0      F       employee     0   

       total_income                   purpose  
12              NaN         to have a wedding  
26              NaN                 education  
29              NaN    building a real estate  
41              NaN  second-hand car purchase  
55              NaN         to have a wedding  
...             ...                       ...  
21489           NaN         purchase of a car  
21495           NaN          wedding ceremony  
21497           NaN       building a property  
21502           NaN    building a real estate  
21510           NaN              car purchase  

[2174 rows x 12 columns]

Aplicando o filtro para apresentar os valores ausentes em ambas as colunas temos exactamente o mesmo total de registos, no entanto, pode ser um pouco arduo confimar se são **exactamente** os mesmos registos sem algum identificador unico para o cliente.

Com base nesta observação vamos tentar validar comparando a igualdade dos dataframes com o metodo `equals()`

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Muito bom trabalho em visualizar como estão os dados nulos das colunas analisadas!

</div>

In [10]:
df_employed_null.equals ( df[ df.total_income.isna() ] )

True

**<font color=green>Temos exactamente o mesmo dataframe</font>**

***
<a id=confirmAusentes>confirmacao dos ausentes</a>

**Validação da percentagem dos valores ausentes em relação ao dataset**

In [11]:
 # Podemos usar o df.isnull().sum() porque ja sabemos que apenas as 2 colunas irão apresentar valores
print(df.isnull().sum() / df.shape[0] * 100.00)

# Alterantiva para apenas as duas colunas:
#print( len(df_employed_null) / df.shape[0] * 100.00 )
#print( df.total_income.isnull().sum() / df.shape[0] * 100.00 )

children             0.000000
days_employed       10.099884
dob_years            0.000000
education            0.000000
education_id         0.000000
family_status        0.000000
family_status_id     0.000000
gender               0.000000
income_type          0.000000
debt                 0.000000
total_income        10.099884
purpose              0.000000
dtype: float64


In [12]:
round( (df.isnull().sum() / df.shape[0] * 100.00).loc['days_employed'])

10

Podemos afirmar que os valores ausentes para ambas as colunas representam aproximadamente **10%** do total de clientes analisados

Os valores ausentes serão tratados [aqui](#trabalhandoAusentes)


### Associação com a coluna `debt` (havia alguma dívida no pagamento do empréstimo)

**No dataframe com os valores null para a coluna `days_employed`, pdemos ver e contar os diferentes valores para a coluna `debt`**

In [13]:
total = df_employed_null.debt.value_counts(dropna=False)

# .mul(x) multiplica os valores por x
# .round(x) apresenta apenas x casas decimais
# .astype(str) converte para string
# + '%' concatena % :)
percent = df_employed_null.debt.value_counts(dropna=False, normalize=True).mul(100).round(1).astype(str) + '%'

# Concatena os dois dataframes resultantes acima, importatente possuirem as mesmas colunas e numero de linhas.
distribuicao = pd.concat([total,percent], axis=1, keys=['Total', '%']) 

>A tabela abaixo apresenta a distribuição na pequena amostra de clientes com valores ausentes

In [14]:
distribuicao

Total      %
0   2004  92.2%
1    170   7.8%

**Conclusão intermediária**


O total de linhas para as tabelas filtradas tanto para as colunas `days_employed` e `total_income` ou ainda a o filtro combinado para ambas as colunas corresponde ao **total de valores ausentes no nosso dataset**. Isto nos transmite alguma segurança em afirmar que não estamos perante a erros em preenchimento do formulário (erro humano) e sim <font color=red>clientes para obtenção do credito que estão desempregados.</font>

**10%** dos dados acredito ser um valor consideravelmente impactante para a analise em curso caso nos proximos passos optemos pela remoção dos registos com dados ausentes, de qualquer modo, pela conclusão obtida, podemos confortavelmente dar um melhor tratamento aos valores ausentes uma vez que trata-se dos clientes desempregados, exemplo substituir o `NaN` por `0`

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Ótima análise Gerson! Suas conclusões estão muito bem embasadas nas suas análises anteriores, muito bem!

</div>

In [15]:
# Vamos investigar clientes que não possuem dados sobre as características identificadas e a coluna com os valores ausentes
df_filtered = df [ ~df.days_employed.isna() ]

In [16]:
# Verificar a distribuição
df_filtered.head(10)

children  days_employed  dob_years            education  education_id  \
0         1   -8437.673028         42    bachelor's degree             0   
1         1   -4024.803754         36  secondary education             1   
2         0   -5623.422610         33  Secondary Education             1   
3         3   -4124.747207         32  secondary education             1   
4         0  340266.072047         53  secondary education             1   
5         0    -926.185831         27    bachelor's degree             0   
6         0   -2879.202052         43    bachelor's degree             0   
7         0    -152.779569         50  SECONDARY EDUCATION             1   
8         2   -6929.865299         35    BACHELOR'S DEGREE             0   
9         0   -2188.756445         41  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   
5  civil partnership                 1      M    business     0     40922.170   
6            married                 0      F    business     0     38484.156   
7            married                 0      M    employee     0     21731.829   
8  civil partnership                 1      F    employee     0     15337.093   
9            married                 0      M    employee     0     23108.150   

                               purpose  
0                purchase of the house  
1                         car purchase  
2                purchase of the house  
3              supplementary education  
4                    to have a wedding  
5                purchase of the house  
6                 housing transactions  
7                            education  
8                     having a wedding  
9  purchase of the house for my family

In [17]:
df_filtered.isna().sum()

children            0
days_employed       0
dob_years           0
education           0
education_id        0
family_status       0
family_status_id    0
gender              0
income_type         0
debt                0
total_income        0
purpose             0
dtype: int64

Se filtramos o dataset para apresentar os registos que não tem `NaN` para a coluna `days_employed` e consequentemente deixamos de ter valores ausentes

**Possíveis motivos para valores ausentes nos dados**

- Nada a acrescentar até o momento

In [18]:
# Verificar a distribuição em todo o conjunto de dados
print(f' {(len(df_filtered) / len(df)) * 100} % do dataset não tem valores ausentes!')

 89.90011614401858 % do dataset não tem valores ausentes!


## Transformação de dados


**Funcao para apresentar a distribuição e o total de volores ausentes**

In [19]:
#"""
#Esta funcao foi criada apenas quando cheguei na ultima coluna e reparei que estava a ser repetitivo em mostrar a 
#distribuicao por value_counts()
#"""

#Por se tratar de uma função podemos trabalhar um pouco mais e apresentar de um modo mais elegante :)

#Recebe 2 argumentos (dataframe com o valor default para variavel df, e o nome da coluna)
#Retorna o dataframe para não termos que envolver numa funcao print()

def ver_distribuicao( dataf = df, col=None): # Não sei porque exigiu um valor default para a 'col'
    
    total = dataf[col].value_counts().reset_index()
    
    #Normalize > Obter a percentagem para cada valor
    #round > Definir o numero de casas decimais para o objecto
    #astype(str) > Converter o valor para (str)
    percent =  (dataf[col].value_counts(normalize=True).reset_index(drop=True) * 100).round(2).astype(str) + '%'

    #Dicionario de listas
    tabela_dist_children = { col: total['index'].astype(str).tolist() ,
                             'Total': total[col].tolist() ,
                             'Percentagem': percent.tolist()}
    
    tmpDf = pd.DataFrame(tabela_dist_children).sort_values('Total', ascending=False)
    
    return tmpDf.style.bar()    

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Função muito bem definida!

</div>

### Coluna `education`

In [20]:
# Vamos ver todos os valores na coluna de educação para verificar se e quais grafias precisarão ser corrigidas

ver_distribuicao(df, 'education')


In [21]:
# Corrija os registros, se necessário

df['education'] = df['education'].str.lower()

df.head()

children  days_employed  dob_years            education  education_id  \
0         1   -8437.673028         42    bachelor's degree             0   
1         1   -4024.803754         36  secondary education             1   
2         0   -5623.422610         33  secondary education             1   
3         3   -4124.747207         32  secondary education             1   
4         0  340266.072047         53  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   

                   purpose  
0    purchase of the house  
1             car purchase  
2    purchase of the house  
3  supplementary education  
4        to have a wedding

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Dados da coluna "education" corrigidos com sucesso

</div>

In [22]:
# Verificando todos os valores na coluna para ter certeza de que os corrigimos

ver_distribuicao(df, 'education')
#df['education'].value_counts()


### Coluna `children`

In [23]:
# Vamos ver a distribuição de valores na coluna `children`

#total = df['children'].value_counts().reset_index()

#Normalize > Obter a percentagem para cada valor
#round > Definir o numero de casas decimais para o objecto
#astype(str) > Converter o valor para (str)
#percent =  (df['children'].value_counts(normalize=True).reset_index(drop=True) * 100).round(2).astype(str) + '%'

#Dicionario de listas
#tabela_dist_children = { 'Children': total['index'].tolist() ,
 #                        'Total': total['children'].tolist() ,
  #                       'Percentagem': percent.tolist()}

#pd.DataFrame(tabela_dist_children).sort_values('Total', ascending=False)

ver_distribuicao(df, 'children')




Pela observação da distribuição dos valores na coluna `children` percebemos que não faz sentido haver valores <font color=red>negativos</font>.

Perante este cenário a abordagem mais correcta seria interagir com os colegas responsáveis pelo preenchimentos do formulário de aplicação ao credito e questionar se tem algum <font color=blue>significado especial</font> ou se quer dizer <font color=blue>nenhuma criança (0)</font> (Sendo estas as nossas hipoteses de significado).

Por se tratar de uma percentagem muito pequena do nosso dataset, apenas **0.22%** iremos considerar o significado **Nenhuma criança (0)** e substiuiremos o valor <font color=red>-1</font> para <font color=blue>0</font>

<div class="alert alert-block alert-danger">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Os dados negativos foram bem tratados! Faltou tratar os dados de 20 filhos, é um número muito alto para termos 76 dados com esse número
    
</div>

In [24]:
# [corrija os dados com base na sua decisão]

df['children'] = df['children'].replace(-1, 0)


**Iremos tratar também os registos onde o número de filhos esta muito fora do padrão (20)**

In [25]:
totalChildren20 = df [df ['children'] == 20]

totalChildren20.head(10)

children  days_employed  dob_years            education  education_id  \
606         20    -880.221113         21  secondary education             1   
720         20    -855.595512         44  secondary education             1   
1074        20   -3310.411598         56  secondary education             1   
2510        20   -2714.161249         59    bachelor's degree             0   
2941        20   -2161.591519          0  secondary education             1   
3302        20            NaN         35  secondary education             1   
3396        20            NaN         56    bachelor's degree             0   
3671        20    -913.161503         23  secondary education             1   
3697        20   -2907.910616         40  secondary education             1   
3735        20    -805.044438         26    bachelor's degree             0   

          family_status  family_status_id gender    income_type  debt  \
606             married                 0      M       business     0   
720             married                 0      F       business     0   
1074            married                 0      F       employee     1   
2510    widow / widower                 2      F       employee     0   
2941            married                 0      F       employee     0   
3302          unmarried                 4      F  civil servant     0   
3396            married                 0      F       business     0   
3671          unmarried                 4      F       employee     0   
3697  civil partnership                 1      M       employee     0   
3735          unmarried                 4      M       employee     0   

      total_income                                   purpose  
606      23253.578                     purchase of the house  
720      18079.798                           buy real estate  
1074     36722.966                      getting an education  
2510     42315.974  transactions with commercial real estate  
2941     31958.391                              to buy a car  
3302           NaN                         profile education  
3396           NaN                      university education  
3671     16200.879                  buying a second-hand car  
3697     18460.911                  buying a second-hand car  
3735     21952.103                        housing renovation

Analisando os 10 primeiros registos, a idade dos clientes `dob_years` nos chama logo a atenção, pois nota-se claramente que há erros nos dados porque não é possível o cliente ter **21 anos e 20 filhos**.

Podemos tentar ver o intervalo de idade para saber a viabilidade de acharmos um numero de filhos medio para o intervalo

In [26]:
filtroValidAge = (df ['children'] == 20) & (df ['dob_years'] > 0)
f"Idade Minima: {df [ filtroValidAge ].dob_years.min()}"

'Idade Minima: 21'

In [27]:
f"Idade Maxima: {df [ filtroValidAge ].dob_years.max()}"

'Idade Maxima: 69'

O numero de filhos medio para o intervalo de idade acima é:

In [28]:
df [ (df.children != 20) & (~df.dob_years.isna()) ].children.mean()

0.4721432234603012

**Menos de 1 filho por cliente** enão podemos atribuir este valor ou então tentar combinar com o estado civil e ver se temos medias diferenciadas para cada estado civil: 

In [29]:
print( df[ (df ['children'] != 20) & (df ['dob_years'] > 0) ].groupby('family_status').children.mean() )

family_status
civil partnership    0.455116
divorced             0.427726
married              0.563462
unmarried            0.224892
widow / widower      0.146162
Name: children, dtype: float64


Ainda assim a media é muito proxima de 0 para cada estado civil.

Sendo assim, por agora, ficamos com duas possibilidades: **Remover os registos ou Atribuir o também o valor 0** 

A nossa escolha foi manter os registos e atribuirmos 0 em substituição do numero de filhos 20.
Para efeitos de comparação, iremos ver a distribuição antes e depois:

In [30]:
ver_distribuicao(df, 'children')

In [31]:
df['children'] = df['children'].replace(20, 0)

ver_distribuicao(df, 'children')

In [32]:
# Verificar a coluna `children` novamente para ter certeza de que está tudo corrigido

Não houve uma mudança significativa uma vez que os clientes com 20 filhos representavam uma percentagem muito baixa em relação a todo dataset

In [33]:
print(f' { round (  (len(totalChildren20) / len(df)) * 100 , 2) }% Tinha 20 filhos')

 0.35% Tinha 20 filhos


<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Muito bom, Gerson! O problema foi corrigido e com ótimas análises complementares :)
    
</div>

### Coluna `days_employed`

**A função foi criada pois faremos exactamente a mesma observação preliminar para as colunas `days_employed` e `dob_years`**
As duas colunas possuem valores numericos

- Ira imprimir e devolver:
-- Total de valores negativos
-- Total de valores positivos
-- Total de valores ausentes


In [34]:
def preliminar_view_num_values(local_dataframe, coluna):
    
    print(f"\nValor minimo: {local_dataframe[coluna].min()}\n")

    print(f"Valor maximo: {local_dataframe[coluna].max()}\n")

    filtro_neg = local_dataframe[coluna] < 0

    total_neg = len( local_dataframe[ filtro_neg ] )
    total_pos = len( local_dataframe[ local_dataframe[coluna] > 0 ] )
    total_ausent= local_dataframe[ coluna ].isna().sum()
    
    percent_neg = total_neg / len(local_dataframe) * 100
    percent_pos = (total_pos / len(local_dataframe) * 100)
    percent_ausent = total_ausent / len(local_dataframe) * 100


    print(f"Total de valores negativos: {total_neg}")
    print(f"{ percent_neg:.2f}%")

    print(f"\nTotal de valores positivos: {len( local_dataframe[ local_dataframe[coluna] >= 0 ] )}")
    print(f"{ percent_pos:.2f}%")

    print(f"\nTotal de valores ausentes: {total_ausent}")
    print(f"{ percent_ausent:.2f}%")
    
    return percent_neg, total_pos, total_ausent
    
    

In [35]:
# Encontre dados problemáticos em `days_employed`, se existirem, e calcule a porcentagem

total_neg, total_pos, total_ausente = preliminar_view_num_values(df, 'days_employed')

filtro_neg = df['days_employed'] < 0


Valor minimo: -18388.949900568383

Valor maximo: 401755.40047533

Total de valores negativos: 15906
73.90%

Total de valores positivos: 3445
16.00%

Total de valores ausentes: 2174
10.10%


Abordando os valores negativos, podemos olhar uma amostra dos dados começando do menor ao maior:

In [36]:
# Aborde os valores problemáticos, se existirem
amostra_valores_neg = df [ filtro_neg ].sort_values('days_employed', ascending=True)

amostra_valores_neg.head(5)

children  days_employed  dob_years            education  education_id  \
16335         1  -18388.949901         61  secondary education             1   
4299          0  -17615.563266         61  secondary education             1   
7329          0  -16593.472817         60    bachelor's degree             0   
17838         0  -16264.699501         59  secondary education             1   
16825         0  -16119.687737         64  secondary education             1   

      family_status  family_status_id gender income_type  debt  total_income  \
16335       married                 0      F    employee     0     29788.629   
4299        married                 0      F    business     0     19609.719   
7329        married                 0      F    employee     0     19951.655   
17838       married                 0      F    employee     0      8198.235   
16825       married                 0      F    employee     0     14644.430   

                           purpose  
16335     real estate transactions  
4299         purchase of the house  
7329           going to university  
17838                 to buy a car  
16825  buy residential real estate

Se observarmos o valor absoluto da conversão de dias para anos ( `days_employed` / 365 ) podemos ver que não faz mais sentido quando olhamos anos de trabalho ao lado da idade do cliente `dob_years`.

In [37]:
amostra_valores_neg['years_employed'] = ( amostra_valores_neg['days_employed'] / 365 ).astype(int) * -1

amostra_valores_neg[['days_employed','years_employed','dob_years']].head()

days_employed  years_employed  dob_years
16335  -18388.949901              50         61
4299   -17615.563266              48         61
7329   -16593.472817              45         60
17838  -16264.699501              44         59
16825  -16119.687737              44         64

Conforme visto anteriormente, os valores negativos correspondem a aproximadamente <font color=blue> **73.90%** </font> de todo o dataset, o que nos transmite a pouca probabilidade de estarmos perante a erros humanos e sim algum erro no sistema ou software usado para a colheita da informação então iremos corrigir estes valores e deixa-los <font color=green>**positivos**</font> 

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Bem corrigido!

</div>

In [38]:
# Podemos usar o metodo .abs() do DataFrame para uma transformação mais facil
df['days_employed'] = df['days_employed'].abs()

In [39]:
# Verifique o resultado - certifique-se de que está corrigido

print(f"Valores ausentes: {df[ 'days_employed' ].isna().sum()}")

filtro_neg = df['days_employed'] < 0
print(f"Valores negativos: {len( df [ filtro_neg ])}")

df [ filtro_neg ]

Valores ausentes: 2174
Valores negativos: 0


Empty DataFrame
Columns: [children, days_employed, dob_years, education, education_id, family_status, family_status_id, gender, income_type, debt, total_income, purpose]
Index: []

### Coluna `dob_years`

#### Iremos chamar a nossa função para a analise preliminar de valores numericos!

In [40]:
# Verifique o `dob_years` para valores suspeitos e conte a porcentagem

total_neg, total_pos, total_ausente  = preliminar_view_num_values(df, 'dob_years')


Valor minimo: 0

Valor maximo: 75

Total de valores negativos: 0
0.00%

Total de valores positivos: 21525
99.53%

Total de valores ausentes: 0
0.00%


Uma vez que estamos a trabalhar com dados de clientes do banco e o objectivo final é ajudar na tomada de decisão para atribuição de credito então por norma para a maioria dos paises os **bancos centrais** não permitem a abertura de conta para <font color=red>**menores de idade**</font>, com excepção de alguns paises que permitem a abertura para **jovens emancipados** com algum tutor ou com os **pais como representante** cuja idade dos jovens compreende dos **16 aos 18 anos**

*Para este caso de estudo iremos desconsiderar excepção apresentada*

> Com base nesta informação podemos concluir que os valores problemáticos são os clientes cuja idade seja inferior a 18, iremos verificar a seguir: 

In [41]:
total = len(df[ df ['dob_years'] < 18 ])
total

101

**Quer dizer que temos <font color=red>101 clientes menores de idade ??**

    Vamos analisar um pouco alguns dados sobre estes clientes e ver o que podemos apurar mais

In [42]:
df[ df ['dob_years'] < 18 ].head(10)

children  days_employed  dob_years            education  education_id  \
99           0  346541.618895          0  secondary education             1   
149          0    2664.273168          0  secondary education             1   
270          3    1872.663186          0  secondary education             1   
578          0  397856.565013          0  secondary education             1   
1040         0    1158.029561          0    bachelor's degree             0   
1149         0     934.654854          0  secondary education             1   
1175         0  370879.508002          0  secondary education             1   
1386         0    5043.219890          0    bachelor's degree             0   
1890         0            NaN          0    bachelor's degree             0   
1898         0  370144.537021          0  secondary education             1   

        family_status  family_status_id gender    income_type  debt  \
99            married                 0      F        retiree     0   
149          divorced                 3      F       employee     0   
270           married                 0      F       employee     0   
578           married                 0      F        retiree     0   
1040         divorced                 3      F       business     0   
1149          married                 0      F       business     0   
1175          married                 0      F        retiree     0   
1386          married                 0      M  civil servant     0   
1890        unmarried                 4      F       employee     0   
1898  widow / widower                 2      F        retiree     0   

      total_income                           purpose  
99       11406.644                               car  
149      11228.230              housing transactions  
270      16346.633                housing renovation  
578      15619.310      construction of own property  
1040     48639.062                      to own a car  
1149     32296.389                   buy real estate  
1175     50231.975  to get a supplementary education  
1386     38483.779                 purchase of a car  
1890           NaN                           housing  
1898     20384.043                      to buy a car

Como a amostra dos 10 primeiros trouxe apenas idade 0 vamos validar a distribuição para os menores de idade

In [43]:
#print(df[ df ['dob_years'] < 18 ]['dob_years'].value_counts())

percent = total/len(df)*100

print(f'\nPercentagem no dataset {percent:.2f}%' )

#Testar passando um dataframe filtrado
ver_distribuicao(df[ df ['dob_years'] < 18 ], 'dob_years')


Percentagem no dataset 0.47%


A distribuição apresenta apenas a idade <font color=red>**0**</font>.

Se olharmos toda a informação (`family_status`,`children`) e as restantes colunas podemos concluir que a hipotese de termos clientes menores de idade foi invalidada e o mais provavel é que estamos diante de <font color=red>valores ausentes</font>. 

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Gostei de sua visualização do dado, está muito organizado e correto!

</div>

Por se tratar de uma distribuição pequena (0.47%) certamente não deverá criar muito impacto se tormarmos a decisão de **preenchermos os valores para algum valor dentro do intervalo de idades existente** como por exemplo a media ou mediana

Para melhor atender este preenchimento podemos considerar alguma/(as) variaveis adicionais como por exemplo o `genero` ou `income_type` ou então as duas variaveis porque se pensarmos bem podemos tentar evitar ter aposentados muito jovens 😅 

In [44]:
# Resolva os problemas na coluna `dob_years`, se existirem

# 1º Adquirir os diferentes valores para o income_type

lista_income_type = df.income_type.unique().tolist()
print(lista_income_type)

# 2º Adquirir a lista de generos:
lista_gender = df.gender.unique().tolist()
print(lista_gender)

#2º Adquirir as media de idade de agrupado por genero para cada income_type

dfGroup = df.groupby(['gender','income_type'])['dob_years'].mean().reset_index()

# Vamos atribuir idades inteiras e não com valores flutuantes 
dfGroup['dob_years'] = dfGroup['dob_years'].astype(int)

dfGroup['dob_years']

['employee', 'retiree', 'business', 'civil servant', 'unemployed', 'entrepreneur', 'student', 'paternity / maternity leave']
['F', 'M', 'XNA']


0     40
1     41
2     40
3     27
4     39
5     59
6     45
7     39
8     38
9     39
10    58
11    58
12    22
13    31
14    24
Name: dob_years, dtype: int64

In [45]:
# Ciclo 1 > Iterar sobre a lista de income_type
total_alterado = 0
for tipo in lista_income_type: # Prime
    
    #Ciclo 2 > Percorrer a lista de generos (felizmente só faz 2 iterações)
    for genero in lista_gender:
        
        #Filtro no dataframe principal para ver quais/quantos serao alterados !
        # !!Idade == 0 & genero == @genero & tipo_emprego == @income_type
        
        cond1 = (df['dob_years'] == 0)
        cond2 = (df['income_type'] == tipo)
        cond3 = (df['gender'] == genero )

        count = len(df.loc[ cond1 & cond2 & cond3 ])
        
        if count > 0: # Quer dizer que há registos para alterar nestas condicoes, entao podemos avancar 
            
            #Pegar a media correspondente, ja nao deve precisar do try uma vez deibaixo do if
            try:
                media = dfGroup.loc[(dfGroup['income_type'] == tipo) & (dfGroup['gender'] == genero )]['dob_years'].values[0]
            except:
                media = 0
        
            total_alterado += count
            #Debug
            print(f'Definindo para "{tipo}" - "{genero}" > registos: {count} - media que sera atribuida: {int( media )}')
        
            #Substituir o valor pela media
            df.loc[ cond1 & cond2 & cond3 , 'dob_years' ] = int(media)

        
if total != total_alterado:
    print(f'{total_alterado} / {total} - O CICLO NAO ALTEROU TODOS OS REGISTOS, VERIFICAR!!!')
else: 
    print(f'\nCiclo Terminado! - {total_alterado}/{total} linhas alteradas')

Definindo para "employee" - "F" > registos: 34 - media que sera atribuida: 40
Definindo para "employee" - "M" > registos: 21 - media que sera atribuida: 39
Definindo para "retiree" - "F" > registos: 19 - media que sera atribuida: 59
Definindo para "retiree" - "M" > registos: 1 - media que sera atribuida: 58
Definindo para "business" - "F" > registos: 14 - media que sera atribuida: 40
Definindo para "business" - "M" > registos: 6 - media que sera atribuida: 39
Definindo para "civil servant" - "F" > registos: 5 - media que sera atribuida: 41
Definindo para "civil servant" - "M" > registos: 1 - media que sera atribuida: 38

Ciclo Terminado! - 101/101 linhas alteradas


<font color=orange>*Acreidto que deve haver alguma maneira mais elegante de realizar esta tarefa, mas por agora só consegui pensar nesta solução 🙁*</font>

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Considero sua solução bem elegante! Utilizar a mediana dos dados seria suficiente, porém sua abordagem está muito bem aplicada :)

</div>

In [46]:
# Verifique o resultado - certifique-se de que está corrigido
df[ df ['dob_years'] < 18 ].head(10)

Empty DataFrame
Columns: [children, days_employed, dob_years, education, education_id, family_status, family_status_id, gender, income_type, debt, total_income, purpose]
Index: []

Ja não temos idades inferiores a 18

Podemos confirmar alguns registos especificos que foram imprimidos mais acima, por exemplo um que tem a coluna `days_employed` com o valor `346541.618895`

In [47]:
# Por algum motivo a execucao abaixo nao retorna o resultado, mas irei persistir em apresentar este cliente!
#df.loc[ (df['days_employed'] == 346541.618895) ]


dfcheck = df.loc[ (df['days_employed'] >= 346541) & (df['days_employed'] < 346542) ]
dfcheck

children  days_employed  dob_years            education  education_id  \
99         0  346541.618895         59  secondary education             1   

   family_status  family_status_id gender income_type  debt  total_income  \
99       married                 0      F     retiree     0     11406.644   

   purpose  
99     car

Pela verificação acima percebemos que a idade foi bem preenchida
Podemos confirmar olhando o dataframe das medias, pois ele possui os campos `income_type` e `gender` para validação

In [48]:
dfGroup [ dfGroup['dob_years'] == dfcheck['dob_years'].values[0] ]

gender income_type  dob_years
5      F     retiree         59

#### Verificacoes Adicionais nos dados preenchidos!


### Coluna  `family_status`

In [49]:
# Vamos ver os valores da coluna

col = 'family_status'

print(f"\nTotal de Valores ausentes: {df[col].isna().sum() }")

ver_distribuicao(df, col)


Total de Valores ausentes: 0


#### Uniformizaçao dos estado civil

Acredito que podemos considerarmos que têm o mesmo significado os seguintes valores:

<font color=blue>married</font> e <font color=blue>civil partnership</font>  

<font color=blue>unmarried</font> e <font color=blue>divorced</font>  

Mas para confirmar felizmente temos a coluna `family_status_id` que representa o identificador para o estado civil
Vamos analisar a distribuicao do identificador:

In [50]:
#df['family_status_id'].value_counts()

ver_distribuicao(df, 'family_status_id')

Para <font color=red>reprovar</font> a hiposete considerada, temos igualmente 5 valores distintos para o id e não 3 apenas 

Podemos comprovar que os 5 estados civis distintos olhando os valores unicos no identificador para cada estado civil 

In [51]:
for estado in df[col].unique():
    print(estado)

    print( df[ (df [col] == estado) ]['family_status_id'].unique() )

married
[0]
civil partnership
[1]
widow / widower
[2]
divorced
[3]
unmarried
[4]


Sem sombra de duvidas cada estado civil tem um significado diferente!

In [52]:
# Aborde os valores problemáticos em `family_status`, se eles existirem

## Sem valores problematicos!

In [53]:
# Verifique o resultado - certifique-se de que está corrigido

## Tudo OK

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Ótima análise!

</div>


### Coluna 'gender'

In [54]:
# Vamos ver os valores na coluna

col = 'gender'

print(f"\nValores ausentes {df[col].isnull().sum()}")

print("Distibuição:")

ver_distribuicao(df, col)



Valores ausentes 0
Distibuição:


A coluna tem uma distribuição um pouco chamativa para uma breve invesitgação do valor XNA, vamos analisar:

In [55]:
df[ df[col] == 'XNA' ]

children  days_employed  dob_years     education  education_id  \
10701         0    2358.600502         24  some college             2   

           family_status  family_status_id gender income_type  debt  \
10701  civil partnership                 1    XNA    business     0   

       total_income          purpose  
10701     32624.825  buy real estate

Claro que será optimo termos o **significado** para este genero, podemos conversar com algum colega só para um apuramento, mas,  numa primeira analise não se nota algo de diferente, mas para confirmar iremos apresentar as primeiras linhas para os outros generos com maior distribuição no dataset.

<div class="alert alert-block alert-warning">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Uma vez que este valor está diferente dos outros dois na categoria e tem apenas uma linha, é provável que seja um dado problemático, então não teria problema excluir esta linha, uma vez que uma linha é uma baixa porcentagem do df

</div>

> <font color=purple>Gerson: Tomei boa nota, obrigado.</font>

In [56]:
df[ df[col] == 'F' ].head()

children  days_employed  dob_years            education  education_id  \
0         1    8437.673028         42    bachelor's degree             0   
1         1    4024.803754         36  secondary education             1   
4         0  340266.072047         53  secondary education             1   
6         0    2879.202052         43    bachelor's degree             0   
8         2    6929.865299         35    bachelor's degree             0   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
4  civil partnership                 1      F     retiree     0     25378.572   
6            married                 0      F    business     0     38484.156   
8  civil partnership                 1      F    employee     0     15337.093   

                 purpose  
0  purchase of the house  
1           car purchase  
4      to have a wedding  
6   housing transactions  
8       having a wedding

In [57]:
df[ df[col] == 'M' ].head()

children  days_employed  dob_years            education  education_id  \
2         0    5623.422610         33  secondary education             1   
3         3    4124.747207         32  secondary education             1   
5         0     926.185831         27    bachelor's degree             0   
7         0     152.779569         50  secondary education             1   
9         0    2188.756445         41  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
5  civil partnership                 1      M    business     0     40922.170   
7            married                 0      M    employee     0     21731.829   
9            married                 0      M    employee     0     23108.150   

                               purpose  
2                purchase of the house  
3              supplementary education  
5                purchase of the house  
7                            education  
9  purchase of the house for my family

Concluindo, nada de anormal com a coluna.

In [58]:
# Aborde os valores problemáticos, se existirem
# Sem valores problematicos

In [59]:
# Verifique o resultado - certifique-se de que está corrigido
# Sem correcoes necessarias

### Coluna `income_type`

In [60]:
# Vamos ver os valores na coluna

col='income_type'

print(f"\nValores ausentes {df[col].isnull().sum()}")

print("Distibuição:")

df_type_dist = ver_distribuicao(df, col)
df_type_dist


Valores ausentes 0
Distibuição:


Tudo parece ok apesar da distribuição pouco uniforme, vamos de forma rápida ver também os valores para os tipos menos frequentes no nosso dataset.

In [61]:
# Aproveitando a funcao que retorna o dataframe da distribuicao,
#posso obter os valores menos frequentes, para isso basta obter o type deste dataframe de acordo a baixa percentagem ( < 1)

#Como é uma string e termina com %, irei primeiro remover o ultimo caracter da string e converter para float

# A funcao ver_distribuicao retorna um objecto do tipo (Styler) é necessário aceder os dados do tipo dataFrame
df_type_dist = df_type_dist.data

df_type_dist['Percentagem'] = df_type_dist['Percentagem'].str[:-1].astype(float)

df_type_dist

income_type  Total  Percentagem
0                     employee  11119        51.66
1                     business   5085        23.62
2                      retiree   3856        17.91
3                civil servant   1459         6.78
4                   unemployed      2         0.01
5                 entrepreneur      2         0.01
6  paternity / maternity leave      1         0.00
7                      student      1         0.00

In [62]:
#Filtrar os valores com a percentagem abaixo de 1
df_type_dist = df_type_dist [ df_type_dist['Percentagem'] < 1.0 ]
df_type_dist

income_type  Total  Percentagem
4                   unemployed      2         0.01
5                 entrepreneur      2         0.01
6  paternity / maternity leave      1         0.00
7                      student      1         0.00

In [63]:
#Para cada income_type deste dataframe auxiliar e mostrar os registos no df principal

#Depois da tentativa abaixo falhada 
#df [ df['income_type'] in df_type_dist['income_type'].values.tolist() ]

#Foi descoberto o metodo magico do dataframe .isin()
df [ df['income_type'].isin( df_type_dist['income_type'].values.tolist() ) ]

children  days_employed  dob_years            education  education_id  \
3133          1  337524.466835         31  secondary education             1   
5936          0            NaN         58    bachelor's degree             0   
9410          0     578.751554         22    bachelor's degree             0   
14798         0  395302.838654         45    bachelor's degree             0   
18697         0     520.848083         27    bachelor's degree             0   
20845         2    3296.759962         39  secondary education             1   

           family_status  family_status_id gender  \
3133             married                 0      M   
5936             married                 0      M   
9410           unmarried                 4      M   
14798  civil partnership                 1      F   
18697  civil partnership                 1      F   
20845            married                 0      F   

                       income_type  debt  total_income  \
3133                    unemployed     1      9593.119   
5936                  entrepreneur     0           NaN   
9410                       student     0     15712.260   
14798                   unemployed     0     32435.602   
18697                 entrepreneur     0     79866.103   
20845  paternity / maternity leave     1      8612.661   

                               purpose  
3133   buying property for renting out  
5936       buy residential real estate  
9410      construction of own property  
14798               housing renovation  
18697                 having a wedding  
20845                              car

Tudo parece ok mesmo para os valores pouco distribuidos.

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Ok!

</div>

In [64]:
# Aborde os valores problemáticos, se existirem
#Sem valores problematicos

In [65]:
# Verifique o resultado - certifique-se de que está corrigido
#Sem correcoes necessarias

### Verificação de duplicatas

#### Verificação para a linha completa

In [66]:
# Verificar duplicatas

total_duplicados = df.duplicated().sum()
total_duplicados

71

Preliminarmente verificamos que temos **71 linhas duplicadas**, vamos olhar um pouco registos duplicados

In [67]:
df [ df.duplicated() ]

children  days_employed  dob_years            education  education_id  \
2849          0            NaN         41  secondary education             1   
3290          0            NaN         58  secondary education             1   
4182          1            NaN         34    bachelor's degree             0   
4851          0            NaN         60  secondary education             1   
5557          0            NaN         58  secondary education             1   
...         ...            ...        ...                  ...           ...   
20702         0            NaN         64  secondary education             1   
21032         0            NaN         60  secondary education             1   
21132         0            NaN         47  secondary education             1   
21281         1            NaN         30    bachelor's degree             0   
21415         0            NaN         54  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
2849             married                 0      F    employee     0   
3290   civil partnership                 1      F     retiree     0   
4182   civil partnership                 1      F    employee     0   
4851   civil partnership                 1      F     retiree     0   
5557   civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
20702            married                 0      F     retiree     0   
21032            married                 0      F     retiree     0   
21132            married                 0      F    employee     0   
21281            married                 0      F    employee     0   
21415            married                 0      F     retiree     0   

       total_income                              purpose  
2849            NaN  purchase of the house for my family  
3290            NaN                    to have a wedding  
4182            NaN                     wedding ceremony  
4851            NaN                     wedding ceremony  
5557            NaN                    to have a wedding  
...             ...                                  ...  
20702           NaN              supplementary education  
21032           NaN                   to become educated  
21132           NaN                   housing renovation  
21281           NaN           buy commercial real estate  
21415           NaN                 housing transactions  

[71 rows x 12 columns]

Se usarmos o parametro `keep=False` poderemos ver o **registo original + o registo(s) duplicado** para melhor visualização do resultado, no entanto, uma vez que verificamos todas as colunas certamente não há erro na informação acima. 

In [68]:
#Sem a ordenação de alguma coluna os registos ficam espalhados pelo dataframe
amostra_duplicados = df [ df.duplicated(keep=False) ].sort_values(['dob_years','purpose']).head(13)
amostra_duplicados

children  days_employed  dob_years            education  education_id  \
15892         0            NaN         23  secondary education             1   
19321         0            NaN         23  secondary education             1   
8853          1            NaN         23  secondary education             1   
20297         1            NaN         23  secondary education             1   
3452          0            NaN         29    bachelor's degree             0   
18328         0            NaN         29    bachelor's degree             0   
4216          0            NaN         30  secondary education             1   
6312          0            NaN         30  secondary education             1   
8629          1            NaN         30    bachelor's degree             0   
21281         1            NaN         30    bachelor's degree             0   
680           1            NaN         30    bachelor's degree             0   
18349         1            NaN         30    bachelor's degree             0   
8490          1            NaN         31  secondary education             1   

           family_status  family_status_id gender    income_type  debt  \
15892          unmarried                 4      F       employee     0   
19321          unmarried                 4      F       employee     0   
8853   civil partnership                 1      F       employee     0   
20297  civil partnership                 1      F       employee     0   
3452             married                 0      M       employee     0   
18328            married                 0      M       employee     0   
4216             married                 0      M       employee     0   
6312             married                 0      M       employee     0   
8629             married                 0      F       employee     0   
21281            married                 0      F       employee     0   
680              married                 0      F  civil servant     0   
18349            married                 0      F  civil servant     0   
8490             married                 0      F       business     0   

       total_income                              purpose  
15892           NaN             second-hand car purchase  
19321           NaN             second-hand car purchase  
8853            NaN                    to have a wedding  
20297           NaN                    to have a wedding  
3452            NaN          buy residential real estate  
18328           NaN          buy residential real estate  
4216            NaN               building a real estate  
6312            NaN               building a real estate  
8629            NaN           buy commercial real estate  
21281           NaN           buy commercial real estate  
680             NaN  purchase of the house for my family  
18349           NaN  purchase of the house for my family  
8490            NaN                purchase of the house

Por não termos um identificador unico para cada linha e não são muitos registos duplicados podemos acreditar que as linhas são de facto duplicadas, sem o id, a questão que encontramos é: *Qual a probabilidade de haver **2 clientes** <font color=blue>com 30 anos, mesmo nivel de educação, mesmo estado civil, mesmo numero de filhos e principalmente mesmo objectivo para aquisição do credito ?</font>*

Certamente não é impossivel, mas pela amostra ser pequena iremos considerar duplicados e criar um esforço colectivo com os restantes colegas para conseguirmos ter identificadores unicos para cada cliente no futuro.

In [69]:
# Aborde as duplicatas, se existirem

#### Remoção dos duplicados e criar novas indices para o dataframe

In [70]:
df = df.drop_duplicates().reset_index(drop=True)

In [71]:
# Última verificação se temos duplicatas
print( f' Total de duplicados depois da remoção: {df.duplicated().sum()}')

 Total de duplicados depois da remoção: 0


<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Remoção de duplicatas bem realizada!

</div>

In [72]:
#Verifique o tamanho do conjunto de dados que você tem agora após suas primeiras manipulações com ele

Felizmente no inicio do processamento gravamos o total de linhas do dataframe na variavel `total_linhas_df_orig` logo [após a leitura do csv](#linhasDfOriginal)

Sendo assim, podemos fazer uma verificação com 99.9% de precisão sobre o tamanho actual do conjunto de dados



In [73]:
if total_linhas_df_orig - total_duplicados != len(df):
    print('ALGO DE ERRADO ACONTECEU NA REMOCAO DE DUPLICADOS')
else:
    print(f'O dataset actual tem o correcto numero de linhas > {total_linhas_df_orig} - {total_duplicados} = {len(df)}')

O dataset actual tem o correcto numero de linhas > 21525 - 71 = 21454


[Descreva seu novo conjunto de dados: diga brevemente o que mudou e qual é a porcentagem das alterações, se houver.]


In [74]:
100 - (len(df) / total_linhas_df_orig) * 100

0.32984901277583845

Podemos informar que os registos duplicados representam apenas **0.32%** dos dados e que não deve impactar as analises futuras

## Trabalhando com valores ausentes

<a id="trabalhandoAusentes"></a>

Voltando ao tema dos valores ausentes, ja verificamos [mais acima](#confirmAusentes) de facto que apenas duas colunas possuem valores ausentes, são elas `days_employed` e `total_income`

Iremos imprimir o total de valores ausentes actual visto que removemos alguns duplicados:

In [75]:
print( f'- A coluna "days_employed" tem { df.days_employed.isna().sum()} valores ausentes')
print( f'- A coluna "total_income" tem { df.total_income.isna().sum()} valores ausentes')

- A coluna "days_employed" tem 2103 valores ausentes
- A coluna "total_income" tem 2103 valores ausentes


In [76]:
# Encontre os dicionários

df [ df.days_employed.isna() ].head(10)

children  days_employed  dob_years            education  education_id  \
12         0            NaN         65  secondary education             1   
26         0            NaN         41  secondary education             1   
29         0            NaN         63  secondary education             1   
41         0            NaN         50  secondary education             1   
55         0            NaN         54  secondary education             1   
65         0            NaN         21  secondary education             1   
67         0            NaN         52    bachelor's degree             0   
72         1            NaN         32    bachelor's degree             0   
82         2            NaN         50    bachelor's degree             0   
83         0            NaN         52  secondary education             1   

        family_status  family_status_id gender    income_type  debt  \
12  civil partnership                 1      M        retiree     0   
26            married                 0      M  civil servant     0   
29          unmarried                 4      F        retiree     0   
41            married                 0      F  civil servant     0   
55  civil partnership                 1      F        retiree     1   
65          unmarried                 4      M       business     0   
67            married                 0      F        retiree     0   
72            married                 0      M  civil servant     0   
82            married                 0      F       employee     0   
83            married                 0      M       employee     0   

    total_income                                   purpose  
12           NaN                         to have a wedding  
26           NaN                                 education  
29           NaN                    building a real estate  
41           NaN                  second-hand car purchase  
55           NaN                         to have a wedding  
65           NaN  transactions with commercial real estate  
67           NaN       purchase of the house for my family  
72           NaN  transactions with commercial real estate  
82           NaN                                   housing  
83           NaN                                   housing

### Restaurar valores ausentes em `total_income`

In [77]:
# Vamos escrever uma função que calcule a categoria de idade

# A funcão devolverá apenas 3 possiveis categorias para a idade dos clientes, no entanto no
#dataset actual não temos menores de 18 anos
#quer dizer que teremos apenas os valores Idoso e Adulto na categoria deste dataset em particular.

def categorizar_idade(linha):
    
    if linha['dob_years'] > 59: return 'Idoso'
    
    if linha['dob_years'] > 18: return 'Adulto'
    
    return 'Jovem'

<font color='gray'> Primeiro não percebi o motivo de criar a função para categorizar a idade
Só quando cheguei [neste ponto aqui](#usarCategoriaIdade) percebi que a categorização da funcão acima não irá ajudar a preencher os valores ausentes de `days_employed`
    
Sendo assim, irei criar uma nova função para dividir as faixas etarias por intervalos de 10 que deve poderá ajudar a distribuir melhor os valores que serão preenchidos nos ausentes.
    
Irei manter a funcao de cima apenas para servir de lição pessoal.
</font>

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Ok, fico feliz que deixou todas as informações bem estabelecidas!

</div>

A funcao ira receber o objecto Series do pandas (linha completa) e fará a validação se a coluna tem um valor inteiro, o retorno será a faixa de idade do cliente

### Funcao para categorizar pela coluna `dob_years`

In [78]:
def categorizar_idade(linha):
    
    try:
        idade = int( linha['dob_years'] )
    
        if idade >= 60: return '60+'

        if 50 <= idade < 60: return '50 - 60'  
        if 40 <= idade < 50: return '40 - 50'  
        if 30 <= idade < 40: return '30 - 40'  
        if 20 <= idade < 30: return '20 - 30'  
        if 10 <= idade < 20: return '10 - 20'  
    
        return '0 - 10'
    except:
        return 'Valor Nao Numerico!'

In [79]:
# Teste se a função funciona

#Primeiro, precisamos criar duas listas. Uma lista deve conter valores e a outra deve ter nomes de coluna DataFrame.
#linhas = [13] # valores de idade e desemprego
#coluna = ['dob_years'] # nomes das colunas
  
#o objecto Series para o teste:
#row = pd.Series(data=linhas, index=coluna) 

# Podemos testar numa unica linha
print( categorizar_idade ( pd.Series (data=[23], index=['dob_years'])  ))
print( categorizar_idade ( pd.Series (data=['50'], index=['dob_years'])  ))
print( categorizar_idade ( pd.Series (data=['A'], index=['dob_years'])  ))


20 - 30
50 - 60
Valor Nao Numerico!


<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Categorização da idade muito bem realizada!

</div>

Aplicando a funcao para todas as linhas do dataset
<a id =categoriaIdade></a>

In [80]:
# Criar coluna nova com base na função
df['age_group'] = df.apply(categorizar_idade, axis=1)

In [81]:
# Verificar como os valores na nova coluna

distr = ver_distribuicao(df, 'age_group')
distr

Podemos fazer uma verificação desta informação contando o total de clientes para uma determinada faixa etaria:

In [82]:
clientes_30_40 = len(df [ (df.dob_years.astype(int) > 29) & (df.dob_years.astype(int) < 40) ])
clientes_30_40

5690

In [83]:
clientes_30_40 == distr.data.Total.values[0]

True

O Resultado corresponde a primeira linha, então esta tudo bem.

A renda do cliente pode depender dos seguintes factores:
- `education`
- `income_type`

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Bem visualizado!

</div>

Então iremos adquirir a media da renda com base nestes factores.

In [84]:
# Crie uma tabela sem valores ausentes e exiba algumas de suas linhas para garantir que ela fique boa

df_sem_ausentes = df[ ~ df.total_income.isna() ]

df_sem_ausentes.head(5)

children  days_employed  dob_years            education  education_id  \
0         1    8437.673028         42    bachelor's degree             0   
1         1    4024.803754         36  secondary education             1   
2         0    5623.422610         33  secondary education             1   
3         3    4124.747207         32  secondary education             1   
4         0  340266.072047         53  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   

                   purpose age_group  
0    purchase of the house   40 - 50  
1             car purchase   30 - 40  
2    purchase of the house   30 - 40  
3  supplementary education   30 - 40  
4        to have a wedding   50 - 60

In [85]:
# Veja os valores médios de renda com base em seus fatores identificados

print('\nMedia com base em education:\n')
print( df_sem_ausentes.groupby(['education'])['total_income'].mean() )

print('\nMedia com base em income_type:\n')
print (df_sem_ausentes.groupby(['income_type'])['total_income'].mean())


Media com base em education:

education
bachelor's degree      33142.802434
graduate degree        27960.024667
primary education      21144.882211
secondary education    24594.503037
some college           29045.443644
Name: total_income, dtype: float64

Media com base em income_type:

income_type
business                       32386.793835
civil servant                  27343.729582
employee                       25820.841683
entrepreneur                   79866.103000
paternity / maternity leave     8612.661000
retiree                        21940.394503
student                        15712.260000
unemployed                     21014.360500
Name: total_income, dtype: float64


In [86]:
# Veja os valores medianos de renda com base em seus fatores identificados

print('Mediana com base em education:')
print( df_sem_ausentes.groupby(['education'])['total_income'].median() )

print('\nMediana com base em income_type:')
print (df_sem_ausentes.groupby(['income_type'])['total_income'].median())


Mediana com base em education:
education
bachelor's degree      28054.5310
graduate degree        25161.5835
primary education      18741.9760
secondary education    21836.5830
some college           25618.4640
Name: total_income, dtype: float64

Mediana com base em income_type:
income_type
business                       27577.2720
civil servant                  24071.6695
employee                       22815.1035
entrepreneur                   79866.1030
paternity / maternity leave     8612.6610
retiree                        18962.3180
student                        15712.2600
unemployed                     21014.3605
Name: total_income, dtype: float64


- Tanto a media como a mediana apresentam valores bem aproximados
- Com base no nivel de educação a media apresenta valores mais altos
- Com base no tipo de renda (entrepreneur,paternity / maternity leave, retiree, student e unemployed) a mediana e a media são iguais 

Irei escolher as medianas com base no tipo de renda para preencher os valores ausentes

In [87]:
df_group = df_sem_ausentes.groupby(['income_type'])['total_income'].median().reset_index()
df_group = df_group.rename(columns={'total_income':'media'}) # é melhor renomear para amanhâ não esquecer.
df_group

income_type       media
0                     business  27577.2720
1                civil servant  24071.6695
2                     employee  22815.1035
3                 entrepreneur  79866.1030
4  paternity / maternity leave   8612.6610
5                      retiree  18962.3180
6                      student  15712.2600
7                   unemployed  21014.3605

In [88]:
#  Escreva uma função que usaremos para preencher os valores ausentes
    
def preencher_renda_ausente (linha):
  
    tipoLinha = linha['income_type']
    
    return df_group.loc[ (df_group['income_type'] == tipoLinha) ]['media'].values[0]


In [89]:
# Verifique se funciona

print( preencher_renda_ausente ( pd.Series( data=['entrepreneur'], index=['income_type'] ) ) )

print( preencher_renda_ausente ( pd.Series( data=['retiree'], index=['income_type'] ) ) )

79866.103
18962.318


In [90]:
# Aplique em todas as linhas

Preciso de aplicar apenas nas linhas do dataframe onde a coluna `total_income` esta `NaN`

In [91]:
df [ df.total_income.isna() ].income_type.value_counts()

employee         1070
business          501
retiree           386
civil servant     145
entrepreneur        1
Name: income_type, dtype: int64

Todos os registos onde o total_income esta `NaN` tem um tipo de renda, então não temos o risco da funcao devolver Nada ou dar erro o o .loc()

In [92]:
 df.loc[ df.total_income.isna(), 'total_income' ] = df[ df.total_income.isna() ].apply(preencher_renda_ausente, axis=1)

In [93]:
# Verifique se temos algum erro

print(f"Valores ausentes apois execucao da funcao : {df.total_income.isna().sum()}")

Valores ausentes apois execucao da funcao : 0


<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Muito bem Gerson! O preenchimento dos valores ausentes foi muito bem realizado!

</div>

Verificando pelo menos um registos que anterior mente estava com `NaN` em total_income

In [94]:
cliente_teste  = df.loc [ (df.dob_years == 65) &
        (df.family_status == 'civil partnership') & (df.purpose == 'to have a wedding') &
        (df.education_id == 1) & (df.gender == 'M') & (df.income_type=='retiree') ]

cliente_teste

children  days_employed  dob_years            education  education_id  \
12         0            NaN         65  secondary education             1   

        family_status  family_status_id gender income_type  debt  \
12  civil partnership                 1      M     retiree     0   

    total_income            purpose age_group  
12     18962.318  to have a wedding       60+

In [95]:
df_group.loc[ (df_group['income_type'] ==  cliente_teste['income_type'].values[0] ) ]['media'].values[0]

18962.318

A verificacao do registo acima mostra que o função foi bem aplicada. 

In [96]:
# Substituir valores ausentes se houver algum erro

# Sem Erros

In [97]:
# Verificar o número de entradas nas colunas

(df.total_income.count() == len(df))

True

<a id=usarCategoriaIdade></a>
###  Restaurar valores em `days_employed`

In [98]:
print(f'total de valores ausentes {df.days_employed.isna().sum()}')

total de valores ausentes 2103


Os valores serão tratados [aqui](#ausentesDaysEmplTratados)

Para o total de dias empregado podemos considerar os seguintes factores que devem condicionar os valores:
- **dob_years** : a idade do cliente
-- Iremos usar esta coluna com a ajuda da categoria de idades criada anteriormente [aqui](#categoriaIdade)


In [99]:
# Distribuição de `days_employed` medianos com base em seus parâmetros identificados

df_days_mean = df.groupby('age_group')['days_employed'].mean().reset_index().rename(columns={'days_employed':'media_days_employed'})

df_days_mean

age_group  media_days_employed
0   10 - 20           633.678086
1   20 - 30          2089.054192
2   30 - 40          4141.951433
3   40 - 50         12286.804503
4   50 - 60        133838.107994
5       60+        286544.143436

In [100]:
# Distribuição de `days_employed` médios com base em seus parâmetros identificados
df_days_median = df.groupby('age_group')['days_employed'].median().reset_index().rename(columns={'days_employed':'mediana_days_employed'})

df_days_median

age_group  mediana_days_employed
0   10 - 20             724.492610
1   20 - 30            1005.629955
2   30 - 40            1598.664181
3   40 - 50            2106.006680
4   50 - 60            4851.384110
5       60+          355229.618218

Apenas para confirmar que não iremos atribuir nenhum total de dias de trabalho impossivel, podemos converter as medias para anos

In [101]:
print("Media Anos Trabalho")
print(df_days_mean['media_days_employed'] / 365)

print("\nMediana Anos Trabalho")
print(df_days_median['mediana_days_employed'] / 365)

Media Anos Trabalho
0      1.736104
1      5.723436
2     11.347812
3     33.662478
4    366.679748
5    785.052448
Name: media_days_employed, dtype: float64

Mediana Anos Trabalho
0      1.984911
1      2.755151
2      4.379902
3      5.769881
4     13.291463
5    973.231831
Name: mediana_days_employed, dtype: float64


Certamente temos algo de errado com as medias para os grupos `50 - 60 +` e com a mediana do grupo `60+`

Se a media/media esta muito alta é porque deve ter valores muito altos na coluna 

Vamos analisar um pouco os dados:
- Ver valores maximos e minimos da coluna `days_employed`

In [102]:
dftmp = df[['dob_years','days_employed']].sort_values('days_employed', ascending=False).head(10)
dftmp

dob_years  days_employed
6948          56  401755.400475
9991          69  401715.811749
7658          61  401675.093434
2156          60  401674.466633
7788          61  401663.850046
4694          56  401635.032697
13396         63  401619.633298
17778         59  401614.475622
10973         56  401591.828457
8360          58  401590.452231

Vamos converter estes valores para anos 

In [103]:
(dftmp['days_employed'] / 365).astype(int)

6948     1100
9991     1100
7658     1100
2156     1100
7788     1100
4694     1100
13396    1100
17778    1100
10973    1100
8360     1100
Name: days_employed, dtype: int64

**Certamente os dados possuem valores muito atipicos para dias/anos de trabalho, sendo impossivel um cliente trabalhar 1100**

<a id=correcaoAtipicosDays></a>

Vamos tentar achar uma valor máximo para esta coluna e atribuir

Podemos ter em conta que para alguns paises o tempo de trabalho para entrar na aposentadoria é de **30 anos para as mulheres** e **35 anos para os homens** e considerar estes valores como o limite do nosso dataset, então poderemos ou remover as linhas que desrespeitam este requisito ou então substituir os valores. Vejamos o total o que representa estas linhas atipicas em relação ao dataset

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Muito bem visualizado! Este ponto é essencial para que os dados façam sentido, definir o valor máximo de anos trabalhados!

</div>

In [104]:
totalM = len ( df [ ((df.days_employed / 365) > 35) & (df.gender=='M') ])
totalF = len ( df [ ((df.days_employed / 365) > 30) & (df.gender=='F') ])
print ( f"Valores atipicos genero M :  {totalM} ")
print ( f"Valores atipicos genero F :  {totalF} ")

print(f" Representa { ((totalM+totalF) / len(df)) * 100 }% do nosso dataset")

Valores atipicos genero M :  652 
Valores atipicos genero F :  2955 
 Representa 16.812715577514684% do nosso dataset


Sendo aproximadamente 17% do nosso dataframe se removermos estas linhas havera de facto um impacto nos resultados sobre o dataset. 

Resta apenas substituirmos

Para esta substituição iremos usar a media de idade dos clientes onde a coluna `days_employed` seja inferior a 35 anos para o genero M e 30 anos para o genero F

In [105]:
maxToWoman = 30*365
maxToMan   = 35*365
print(f"Valor Maximo para genero F  {maxToWoman}")
print(f"Valor Maximo para genero M  {maxToMan}")

Valor Maximo para genero F  10950
Valor Maximo para genero M  12775


Adquirindo as medias para as condicoes mencionadas acima:

In [106]:

#Ja excluimos os M atipicos
dfMediaDays_tmp = df[ ((df.days_employed / 365) <= 35)  & (df.gender=='M') & (~df.days_employed.isna()) ]
mediasDias_M = dfMediaDays_tmp.days_employed.mean()

#Iremos excluir os F atipicos também
dfMediaDays_tmp = df[ ((df.days_employed / 365) <= 30)  & (df.gender=='F') & (~df.days_employed.isna()) ]
mediasDias_F = dfMediaDays_tmp.days_employed.mean()

print(f"Media para o genero M : {mediasDias_M}" )
print(f"Media para o genero F : {mediasDias_F}" )


Media para o genero M : 2048.1439616751886
Media para o genero F : 2368.435771791471


Iremos atribuir estes valores, lembrando que queremos alterar a seguinte qtd de linhas:
- M

In [107]:
totalM

652

- F

In [108]:
totalF

2955

Sendo assim vamos usar o mesmo filtro que nos retornou estes totais [aqui acima](correcaoAtipicosDays)

In [109]:
filtroM = ( (df.days_employed / 365) > 35) & (df.gender=='M') 
filtroF = ( (df.days_employed / 365) > 30) & (df.gender=='F')


df.loc[ filtroM, 'days_employed' ] = mediasDias_M

df.loc[ filtroF, 'days_employed' ] = mediasDias_F


<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Seu código está bem formulado para corrigir os valores anômalos. Gostei muito de sua utilização do máximo para homens e mulheres para trabalhar

</div>

Como ainda temos a variavel abaixo com as medias anterior:

In [110]:
#print("Media Anos Trabalho")
#(df_days_mean['media_days_employed'] / 365).astype(int)
df_days_mean

age_group  media_days_employed
0   10 - 20           633.678086
1   20 - 30          2089.054192
2   30 - 40          4141.951433
3   40 - 50         12286.804503
4   50 - 60        133838.107994
5       60+        286544.143436

Vamos comparar com as novas medias:

In [111]:
df_days_mean_new = df.groupby('age_group')['days_employed'].mean().reset_index().rename(columns={'days_employed':'media_days_employed'})

print("NOVA Media Anos Trabalho")
(df_days_mean_new)

NOVA Media Anos Trabalho


age_group  media_days_employed
0   10 - 20           633.678086
1   20 - 30          1215.139072
2   30 - 40          2025.236406
3   40 - 50          2666.923473
4   50 - 60          2670.945498
5       60+          2482.163028

Convertendo em anos:

In [112]:
df_days_mean_new.media_days_employed / 365

0    1.736104
1    3.329148
2    5.548593
3    7.306640
4    7.317659
5    6.800447
Name: media_days_employed, dtype: float64

**Temos valores mais normais para os dias/anos de trabalho por faixa etaria**

In [113]:
# Vamos escrever uma função que calcule médias ou medianas (dependendo da sua decisão) com base no seu parâmetro identificado

# O calculo das medias com base na faixa etaria foi feito e armazenado no dataframe df_days_mean_new acima 
#após correção dos dados atipicos na coluna days_employed
#Entao resta que a funcao faça atribuicao aos valores ausentes da coluna days_employed

#Muito parecida a funcao preencher_renda_ausente criada acima, pois a origem das medias também das é um df separado:
#def preencher_renda_ausente (linha):
 
#    tipoLinha = linha['income_type']   
#    return df_group.loc[ (df_group['income_type'] == tipoLinha) ]['media'].values[0]

def atribuir_days_ausentes(linha):
    
    try:
        grupo_idade_linha = linha['age_group']
    
        return df_days_mean_new.loc[ (df_days_mean_new['age_group'] == grupo_idade_linha) ]['media_days_employed'].values[0]

    except:
        return 0


In [114]:
# Verifique se a função funciona

print( atribuir_days_ausentes ( pd.Series (data=['60+'], index=['age_group'])  ))

print( atribuir_days_ausentes ( pd.Series (data=['30 - 40'], index=['age_group'])  ))

2482.1630282778474
2025.2364061062533


Lembramos mais uma vez o total de valores ausentes para a coluna e que não foi alterado mesmo após a modificação acima:

[aqui](#usarCategoriaIdade)


In [115]:
print(f'total de valores ausentes {df.days_employed.isna().sum()}')

total de valores ausentes 2103


<a id=ausentesDaysEmplTratados></a>

In [116]:
# Aplicar função

#Sobre os valores ausentes apenas

df.loc[ df.days_employed.isna(), 'days_employed' ] =  df[ df.days_employed.isna() ].apply( atribuir_days_ausentes, axis=1 )

In [117]:
# Verifique se a função funcionou

print(f'total de valores ausentes {df.days_employed.isna().sum()}')

total de valores ausentes 0


<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Valores ausentes na coluna 'days_employed' muito bem realizada! Código bem estruturado

</div>

In [118]:
# Substituir valores ausentes

# Sem mais valores ausentes

In [119]:
df.days_employed.count() == len(df)

True

O total de valores para a coluna `days_employed` corresponde ao numero de valores em outras colunas.

In [120]:
# Verifique as entradas em todas as colunas - certifique-se de corrigir todos os valores ausentes

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21454 entries, 0 to 21453
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21454 non-null  int64  
 1   days_employed     21454 non-null  float64
 2   dob_years         21454 non-null  int64  
 3   education         21454 non-null  object 
 4   education_id      21454 non-null  int64  
 5   family_status     21454 non-null  object 
 6   family_status_id  21454 non-null  int64  
 7   gender            21454 non-null  object 
 8   income_type       21454 non-null  object 
 9   debt              21454 non-null  int64  
 10  total_income      21454 non-null  float64
 11  purpose           21454 non-null  object 
 12  age_group         21454 non-null  object 
dtypes: float64(2), int64(5), object(6)
memory usage: 2.1+ MB


In [122]:
df.describe()

children  days_employed     dob_years  education_id  \
count  21454.000000   21454.000000  21454.000000  21454.000000   
mean       0.471287    2260.514208     43.476088      0.817097   
std        0.751071    1773.607275     12.224853      0.548674   
min        0.000000      24.141633     19.000000      0.000000   
25%        0.000000    1023.662702     33.000000      1.000000   
50%        0.000000    2048.143962     42.000000      1.000000   
75%        1.000000    2666.923473     53.000000      1.000000   
max        5.000000   12747.577578     75.000000      4.000000   

       family_status_id          debt   total_income  
count      21454.000000  21454.000000   21454.000000  
mean           0.973898      0.081150   26451.212929  
std            1.421567      0.273072   15709.968189  
min            0.000000      0.000000    3306.762000  
25%            0.000000      0.000000   17219.817250  
50%            0.000000      0.000000   22815.103500  
75%            1.000000      0.000000   31331.348000  
max            4.000000      1.000000  362496.645000

In [123]:
df.dtypes

children              int64
days_employed       float64
dob_years             int64
education            object
education_id          int64
family_status        object
family_status_id      int64
gender               object
income_type          object
debt                  int64
total_income        float64
purpose              object
age_group            object
dtype: object

## Categorização de dados


In [124]:
# Exiba os valores dos dados selecionados para categorização


### Verificacao dos valores unicos

In [125]:
# Verifique os valores exclusivos

for col in df.columns.tolist():
    print(f"{col} - valores exclusivos:\n {df[col].unique()}\n")

#print(f"education - Valores exclusivos \n{df.education.unique()}")

#print(f"\nfamily_status - Valores exclusivos \n{df.family_status.unique()}")

#print(f"\nincome_type - Valores exclusivos \n{df.income_type.unique()}")

#print(f"\nchildren - Valores exclusivos \n{df.children.unique()}")

#print(f"\n debt - Valores exclusivos \n{df.debt.unique()}")

#print(f"\npurpose - Valores exclusivos \n{df.purpose.unique()}")


children - valores exclusivos:
 [1 0 3 2 4 5]

days_employed - valores exclusivos:
 [8437.67302776 4024.80375385 5623.42261023 ... 2113.3468877  3112.4817052
 1984.50758853]

dob_years - valores exclusivos:
 [42 36 33 32 53 27 43 50 35 41 40 65 54 56 26 48 24 21 57 67 28 63 62 47
 34 68 25 31 30 20 49 37 45 61 64 44 52 46 23 38 39 51 59 29 60 55 58 71
 22 73 66 69 19 72 70 74 75]

education - valores exclusivos:
 ["bachelor's degree" 'secondary education' 'some college'
 'primary education' 'graduate degree']

education_id - valores exclusivos:
 [0 1 2 3 4]

family_status - valores exclusivos:
 ['married' 'civil partnership' 'widow / widower' 'divorced' 'unmarried']

family_status_id - valores exclusivos:
 [0 1 2 3 4]

gender - valores exclusivos:
 ['F' 'M' 'XNA']

income_type - valores exclusivos:
 ['employee' 'retiree' 'business' 'civil servant' 'unemployed'
 'entrepreneur' 'student' 'paternity / maternity leave']

debt - valores exclusivos:
 [0 1]

total_income - valores exclusivos:

**Podemos categorizar as seguintes colunas**

- `children` e dizer simplesmente se tem ou não filhos, `True` ou `False` para um filtro rapido pelo dataset

- `debt` a coluna tem apenas 2 valores, 0 ou 1 o que nos leva a categorizar do mesmo modo (sim/nao) `True` ou `False`
- `education` podemos categorizar dizendo se o cliente tem `high level education` ou `nao`, novamente posso resumir em `True` ou `False` para uma nova coluna `has_some_high_education`

<div class="alert alert-block alert-warning">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Como temos poucas categorias em education, não é necessário categorizar esta coluna!

</div>

> <font color=purple>Gerson: Tomei boa nota, obrigado.</font>

### Funcao para categorizar pela coluna `children`

In [126]:
# Vamos escrever uma função para categorizar os dados com base em tópicos comunss
### Funcao para categorizar a coluna `children`
def categorizar_children(row):
    
    if row['children'] > 0 : return True

    return False

### Funcao para categorizar pela coluna `education`

In [127]:
def categorizar_high_education(row):
    
    education_level = row['education']
    
    if education_level == 'primary education' or education_level == 'secondary education': return False
    
    return True

### Funcao para categorizar pela coluna `debt`

In [128]:
def categorizar_has_debt(row):
    
    if row['debt'] == 0 : return "Nao tem divida"

    return "Tem divida"
    


<a id=categRendaCliente></a>

### **Categorizar a renda do cliente em `baixo`,`medio` e `alto`**

Será criada igualmente uma função para esta categorização com base a renda mensal do cliente.

Precisamos então de definir os intervalos numericos da renda
Esta categorização com base no intervalo da renda mensal faz todo sentido quando percebemos qual o salário minimo do pais em questão e qual o custo de vida no mesmo pais, caso tenhamos esta informação poderemos fazer uma categorização mais realista para os clientes.

In [129]:
print(df.total_income.mean() )
print(df.total_income.median() )
print(df.total_income.max())
print(df.total_income.min())

26451.212928894376
22815.103499999997
362496.645
3306.762


Como a renda maxima do nosso conjunto é de 362496, irei contar quantos estao acima da media:

In [130]:
acima_media = len ( df[df.total_income > df.total_income.mean() ]  )
acima_media

8171

In [131]:
acima_media / len(df) * 100

38.086137783163984

Como temos **38%** de clientes acima da media, e a diferença entre a media e o maximo é mais **+1 casa decimal** irei adicionar uma **outra categoria** para estes clientes `muito alto`

Porque para min não faz muito sentido o cliente estar pelo menos **13 vezes** acima da renda media e ser considerado apenas renda alta. 

- 0 - 10_000 > `Baixo`
- 10_001 - 30_000 > `Medio`
- 30_001 - 60_000 > `Alta`
- 60_001+ > `muito alto`

### Funcao para categorizar a `renda`

In [132]:
def categorizar_renda(linha):
    
    try:
        renda = ( linha['total_income'] )

        if renda >= 60_001: return 'muito alto'

        if 30_000 <= renda < 60_000: return 'alto'  
        if 10_000 <= renda < 30_000: return 'medio'  

        return 'baixo'
    except:
        return 'Valor Nao Numerico!'
    

#df['income_level'] = df.apply(categorizar_renda, axis=1)
#ver_distribuicao(df, 'income_level')

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Categorias muito bem colocadas para a renda! Sua função está corretíssima

</div>

Teste da funcao

In [133]:
categorizar_renda ( pd.Series( data=[1_002.0], index=['total_income'] ))

'baixo'

Aplicação no dataset e observaçao da distribuicao

In [134]:
df['income_level'] = df.apply(categorizar_renda, axis=1)
ver_distribuicao(df, 'income_level')

In [135]:
# Crie uma coluna com as categorias e conte os valores para elas

df['has_children'] = df.apply(categorizar_children, axis=1)

In [136]:
# Crie uma coluna com as categorias e conte os valores para elas

df['has_debt'] = df.apply(categorizar_has_debt, axis=1)

In [137]:
# Examinar todos os dados numéricos em sua coluna selecionada para categorização

In [138]:
# Obter estatísticas resumidas para a coluna
ver_distribuicao(df,'has_children')

Aplicar a funcao para categorizar com base a coluna `education`

In [139]:
df['has_some_high_education'] = df.apply(categorizar_high_education, axis=1)

In [140]:
ver_distribuicao(df,'has_children')

In [141]:
# Criar função para categorização em diferentes grupos numéricos com base em intervalos
# Feito

In [142]:
# Criar coluna com categorias
# Feito

In [143]:
# Conte os valores de cada categoria para ver a distribuição
# Feito

**A coluna `age_group` que criamos [aqui](#categoriaIdade) é um bom exemplo para a categorização em grupos numericos**

Vejamos novamente a distribuição:

In [144]:
ver_distribuicao(df,'age_group')

<a id=uniformizarPurpose></a>
**Iremos adicionalmente uniformizar a coluna `purpose` para atender melhor a ultima hipotese**

Actualmente temos o conjunto de valores para a coluna `purpose`

In [145]:
listaPurposeOrig = sorted ( df.purpose.unique().tolist() )
listaPurposeOrig[:]

['building a property',
 'building a real estate',
 'buy commercial real estate',
 'buy real estate',
 'buy residential real estate',
 'buying a second-hand car',
 'buying my own car',
 'buying property for renting out',
 'car',
 'car purchase',
 'cars',
 'construction of own property',
 'education',
 'getting an education',
 'getting higher education',
 'going to university',
 'having a wedding',
 'housing',
 'housing renovation',
 'housing transactions',
 'profile education',
 'property',
 'purchase of a car',
 'purchase of my own house',
 'purchase of the house',
 'purchase of the house for my family',
 'real estate transactions',
 'second-hand car purchase',
 'supplementary education',
 'to become educated',
 'to buy a car',
 'to get a supplementary education',
 'to have a wedding',
 'to own a car',
 'transactions with commercial real estate',
 'transactions with my real estate',
 'university education',
 'wedding ceremony']

In [146]:
print (f"Total de motivos: {len(listaPurposeOrig)}")

Total de motivos: 38


A nosso ver, temos `duplicados` **implicitos** e podemos transformar para apresentar no final um relatorio mais simplificado

In [147]:

palavrasChave = ['car','house','real estate','education','property','housing','wedding']

for chave in palavrasChave:
    
    listaTemp = [ valor for valor in listaPurposeOrig if chave in valor ]
    
    print(f"Temos {len(listaTemp)} linhas com a palavra chave {chave}")
    
    df.purpose.replace(listaTemp, chave , inplace=True)

    
listaPurposeNew = sorted ( df.purpose.unique().tolist() )
print(f"Total de motivos após a uniformização: {len(listaPurposeNew)}")

Temos 9 linhas com a palavra chave car
Temos 3 linhas com a palavra chave house
Temos 7 linhas com a palavra chave real estate
Temos 7 linhas com a palavra chave education
Temos 4 linhas com a palavra chave property
Temos 3 linhas com a palavra chave housing
Temos 3 linhas com a palavra chave wedding
Total de motivos após a uniformização: 9


<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Ótimo! A categorização de purpose foi muito bem realizada, é essencial dividir em poucas categorias para remover as duplicatas implícitas.

</div>

In [148]:
ver_distribuicao(df, 'purpose')

Ja temos uma melhoria na categorização, mas, podemos fazer alguns ajustes manuais pendentes:

In [149]:
df.purpose.replace('housing', 'real estate' , inplace=True)
df.purpose.replace('house', 'real estate' , inplace=True)
df.purpose.replace('going to university', 'education' , inplace=True)
df.purpose.replace('to become educated', 'education' , inplace=True)

In [150]:
ver_distribuicao(df, 'purpose')

**Caso os colegas queiram realmente o maximo de detalhes na coluna `purpose`, podemos descartar esta transformação.**

## Verificar as Hipóteses


### Existe uma correlação entre o nível de renda e do pagamento em dia?

In [151]:
df.head()

children  days_employed  dob_years            education  education_id  \
0         1    8437.673028         42    bachelor's degree             0   
1         1    4024.803754         36  secondary education             1   
2         0    5623.422610         33  secondary education             1   
3         3    4124.747207         32  secondary education             1   
4         0    2368.435772         53  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   

       purpose age_group income_level  has_children        has_debt  \
0  real estate   40 - 50         alto          True  Nao tem divida   
1          car   30 - 40        medio          True  Nao tem divida   
2  real estate   30 - 40        medio         False  Nao tem divida   
3    education   30 - 40         alto          True  Nao tem divida   
4      wedding   50 - 60        medio         False  Nao tem divida   

   has_some_high_education  
0                     True  
1                    False  
2                    False  
3                    False  
4                    False

In [152]:
# Verifique os dados das crianças e do pagamento em dia

dpivot = df.pivot_table(index='children', columns='has_debt', values='has_children', aggfunc=['count'], margins=True, fill_value=0)

# Calcular a taxa de inadimplência com base no número de filhos
dpivot

count                  
has_debt Nao tem divida Tem divida    All
children                                 
0                 13142       1072  14214
1                  4364        444   4808
2                  1858        194   2052
3                   303         27    330
4                    37          4     41
5                     9          0      9
All               19713       1741  21454

In [153]:
dpivot['% nao tem divida'] = ((dpivot.loc[:]["count"]['Nao tem divida'] / dpivot.loc[:]['count']['All']) * 100 ).round(1).astype(str) + '%'

dpivot['% tem divida'] = ((dpivot.loc[:]["count"]['Tem divida'] / dpivot.loc[:]['count']['All']) * 100 ).round(1).astype(str) + '%'

#for i, r in dpivot.iterrows():
    
#dpivot.style.bar()

#(dpivot.loc[ 20 ][0] / len(df) * 100).round(1).astype(str) + '% Dos clientes não têm divida'

In [154]:
dpivot

count                   % nao tem divida % tem divida
has_debt Nao tem divida Tem divida    All                              
children                                                               
0                 13142       1072  14214            92.5%         7.5%
1                  4364        444   4808            90.8%         9.2%
2                  1858        194   2052            90.5%         9.5%
3                   303         27    330            91.8%         8.2%
4                    37          4     41            90.2%         9.8%
5                     9          0      9           100.0%         0.0%
All               19713       1741  21454            91.9%         8.1%

<font color=orange>Ainda não tenho o dominio do uso das tabelas pivô mas acredito que a tabela apresenta o resultado pretendido para a analise </font>

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Está correto sim!

</div>

**Conclusão**

Podemos perceber que o para os clientes analisados, o numero de filhos não tem sido um grande factor para as dividas não pagas

- ~~Os clientes com **mais dividas** de acordo numero de filhos são os que têm **20 filhos**, mas ainda assim é um universo de apenas **8 clientes**, que representa **10%** num conjunto de **1741 clientes com divida**~~
- Os clientes com **menos dividas** são os que tem um total de **5 filhos**


<div class="alert alert-block alert-warning">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Bem analisado! Porém, os dados para 20 filhos são estranhos, ao lidar com eles lá em cima sua conclusão pode talvez mudar :)

</div>

> Obrigado pela dica, tomei boa nota caro Lourenço.

Corrigindo a conclusão o primeiro ponto será:

- Os clientes com **mais dividas** de acordo numero de filhos são os que **não têm filhos**, sendo um universo de  **14214 clientes**, 1072 clientes têm dividas, que representa **7.5%**, apesar da percentagem ser menor ainda assim é a amostra maior.

Para minimizar os erros, o calculo da percentagem para a tabela pivô será retornado por uma função.

In [155]:

def add_col_percent(dataf, subindice, coluna ):
    
    return ((dataf.loc[:][subindice][coluna] / dataf.loc[:][subindice]['All']) * 100 ).round(1).astype(str) + '%'

### Existe uma correlação entre o status familiar e o pagamento em dia?

In [156]:
# Verifique os dados de status da família e do pagamento em dia

dpivot = df.pivot_table(index='family_status', columns='has_debt',values='debt', aggfunc=['count'], margins=True, fill_value=0)

dpivot['% nao tem divida'] = add_col_percent(dpivot,'count','Nao tem divida')
dpivot['% tem divida'] = add_col_percent(dpivot,'count','Tem divida')


# Calcular a taxa padrão com base no status da família

dpivot.style.bar( subset = (dpivot.index.tolist()[:-1] , dpivot.columns.tolist()[:3]) )

**Conclusão**

- Pela apresentação podemos inferir que:
-- Os clientes `married` representam o maior numero no nosso conjunto de dados com **12339** registos, e **7.5%** deles têm divida não paga 

-- Os clientes com o estado familiar `unmaried` e `civil partnership` apesar de não serem a maioria ocupam a maior taxa para com **9.8%** e **9.3%** de dividas não pagas respectivamente

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Bem avaliado!

</div>

### Existe uma correlação entre o status familiar e o pagamento em dia?

In [157]:
# Verifique os dados do nível de renda e do pagamento em dia

Ao ler este pedido temos clareza que precisamos **categorizar o a renda mensal** dos clientes

Esta actividade foi feita [Aqui](#categRendaCliente)

Apos a categorização, podemos seguir:

In [158]:
dpivot = df.pivot_table(index='income_level', columns='has_debt',values='debt', aggfunc=['count'], margins=True, fill_value=0)

dpivot['% de clientes sem divida'] = add_col_percent(dpivot,'count','Nao tem divida')
dpivot['% de clientes com divida'] = add_col_percent(dpivot,'count','Tem divida')


In [159]:
# Calcular a taxa de inadimplência com base no nível de renda
dpivot.style.bar( subset = (dpivot.index.tolist()[:-1] , dpivot.columns.tolist()[:-2]) )

**Conclusão**

Com base no resultado apresentado podemos informar que a maioria dos clientes tem o nivel de renda `medio` de acordo a nossa categorização.

A taxa pode ser observada nas duas ultimas colunas temporarias: `% de clientes sem divida` e `% de clientes com divida`

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Ok!

</div>

**Como a finalidade do crédito afeta a taxa de inadimplência?**

Para esta ultima tarefa faremos uma ultima transformação nos dados que consistem em uniformizar alguns valores para a coluna `purpose` [Aqui.](#uniformizarPurpose).


In [160]:
# Confira os percentuais de inadimplência para cada finalidade de crédito e analise-os

dpivot = df.pivot_table(index='purpose', columns='has_debt',values='debt', aggfunc=['count'], margins=True, fill_value=0)

dpivot['% de clientes sem divida'] = add_col_percent(dpivot,'count','Nao tem divida')
dpivot['% de clientes com divida'] = add_col_percent(dpivot,'count','Tem divida')

dpivot.style.bar( subset = (dpivot.index.tolist()[:-1] , dpivot.columns.tolist()[:-2]) )

**Conclusão**

Com a apresentação acima, podemos informar que os clientes com a taxa de inadimplência maior **(9.4%)** têm como objectivo destinar a aquisição do credito para **carro/carros**

Segue os diferentes motivos preenchidos no conjunto de dados associados a **carro**

In [161]:
[ motivo for motivo in listaPurposeOrig if 'car' in motivo]

['buying a second-hand car',
 'buying my own car',
 'car',
 'car purchase',
 'cars',
 'purchase of a car',
 'second-hand car purchase',
 'to buy a car',
 'to own a car']

<div class="alert alert-block alert-success">
<b>Comentário do corretor</b> <a class="tocSkip"></a>

Suas análises estão muito bem feitas, Gerson! Parabéns pelo projeto!

</div>

# Conclusão Geral 

<font color=gray>
O projecto foi certamente desafiador não tanto pela complexidade mas sim pela extensão e confesso que houve um pouco de dificuldade em entender ao certo as solicitações feitas, de qualquer forma, acredito que fui uma experiência muito boa para consolidar os conhecimentos.

Quando percebi que temos a liberdade na tomada de decisões fiquei um pouco desorientado no sentido de querer tratar tudo fora do tempo certo e no tempo certo soube que precisava andar e não correr para fazer o melhor progresso.
</font>




Em relação aos valores ausentes no dataset, a solução mais rápida mais eficaz e que pode custar um pouco mais de tempo
para os utilizadores que preenchem os dados seria aplicar a obrigatoriedade no preenchimento dos formulários. 

Em relação aos registos duplicados, acredito que a criação de uma coluna que identifica exclusivamente cada cliente e a 
validação da mesma no acto de submissão do formulário.